# Configuration file for launching tasks on Compute Canada

jobs: 200
local-cores: 1

jobscript: "slurm-jobscript.sh"
#cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"

restart-times: 3
max-jobs-per-second: 1
max-status-checks-per-second: 10
latency-wait: 60
rerun-incomplete: True
printshellcmds: True
use-conda: True
keep-going: True
