# Configuration file for launching tasks on Compute Canada

jobs: 240
local-cores: 1

jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"

default-resources: [cpus=1, mem_mb=4000, nodes=1, time="01:00:00"]
restart-times: 3
max-jobs-per-second: 1
max-status-checks-per-second: 10
latency-wait: 60
rerun-incomplete: True
printshellcmds: True
use-conda: True
keep-going: True
