# Sample IDs as list
samples: ../resources/testSamples.txt
chromosomes: ../resources/chromosome_file.txt

results_prefix: ../results_test
data_prefix: /scratch/research/projects/trifolium/toronto_gwsd/data

paths:
  temp_dir: /scratch/santang3/tmp 

files:
  reference_genome: /scratch/research/references/trifolium/repens/GCA_005869975.1_AgR_To_v5/GCA_005869975.1_AgR_To_v5_genomic.fna

variant_calling:
  sample: s_117_6  # Name of representative sample (i.e., with 'average' genome-wide coverage)
  nodes_per_chrom: 1
  cores_per_node: 30
