# Sample IDs as list
samples: ../resources/sequencedPlants_phenotypesHabitat.txt
chromosomes: ../resources/chromosome_file.txt

results_prefix: ../results
raw_read_prefix: /scratch/research/projects/trifolium/toronto_gwsd/data
temp_dir: /scratch/santang3/tmp 

files:
  reference_genome: /scratch/research/references/trifolium/repens/GCA_005869975.1_AgR_To_v5/GCA_005869975.1_AgR_To_v5_genomic.fna
  gff: /scratch/research/references/trifolium/repens/GCA_005869975.1_AgR_To_v5/annotation_file/TrR.v5.renamed_reformated.gtf.gz

# Samples to exclude based on QC (e.g., different species, low coverage, etc.) 
samples_to_exclude: ['7_14', '54_9', '97_4', '23_12', '23_17']

freebayes:
  sample: s_117_6  # Name of representative sample (i.e., with 'average' genome-wide coverage)
  nodes_per_chrom: 1
  cores_per_node: 30
