# Sample IDs as list
samples: ../resources/sequencedPlants_phenotypesHabitat.txt
chromosomes: ../resources/chromosome_file.txt

results_prefix: ../results
data_prefix: /scratch/santang3/data 

paths:
  temp_dir: /scratch/santang3/tmp 

files:
  reference_genome: /scratch/n/nessrobe/santang3/data/ref_genome/GCA_005869975.1_AgR_To_v5_genomic.fna
  gff: /scratch/n/nessrobe/santang3/data/gff/TrR.v5.renamed_reformated.gtf.gz

variant_calling:
  sample: s_7_7
  nodes_per_chrom: 12
  cores_per_node: 40
