# Sample IDs as list
samples: ../resources/low1_libraryConcentrations.csv
chromosomes: ../resources/chromosome_file.txt

results_prefix: ../results
raw_read_prefix: /scratch/santang3/data 
temp_dir: /scratch/santang3/tmp 

files:
  reference_genome: /scratch/n/nessrobe/santang3/clover-ref/ref_genome/GCA_005869975.1_AgR_To_v5_genomic.fna
  gff: /scratch/n/nessrobe/santang3/clover-ref/gff/TrR.v5.renamed_reformated.gtf.gz

# Samples to exclude based on QC (e.g., different species, low coverage, etc.) 
#samples_to_exclude: ['s_7_14', 's_54_9', 's_97_4', 's_23_12', 's_23_17']

cluster:
  cores_per_node: 40

species_id:
  num_nt_db_files: 33  # Number of database files for NCBI's nt database (ftp://ftp.ncbi.nlm.nih.gov/blast/db/)

# Samples to exclude based on QC
samples_to_exclude: ["Calgary_25_13", "Linkoping_8_8", "Melbourne_2_3", "Paris_15_14", "Paris_3_9"]
