# Sample IDs as list
samples: ../resources/glue_pc_sampleSheet.txt 
chromosomes: ../resources/chromosome_file.txt
gff: ../resources/TrR.v5.renamed_reformated.gtf.gz

# Path prefixes
results_prefix: /home/santang3/scratch/glue/pc/results
temp_dir: /home/santang3/scratch/glue/tmp
glue_dnaSeqQC_workflow: 
  snakefile: /home/santang3/scratch/glue/dnaSeqQC/glue_dnaSeqQC/workflow/Snakefile
  raw_read_prefix: /home/santang3/projects/def-johnso73/raw_data
  samples: ../resources/glue_pc_sampleSheet.txt
  chromosomes: ../resources/chromosome_file.txt
  results_prefix: /home/santang3/scratch/glue/dnaSeqQC/results
  gff: ../resources/TrR.v5.renamed_reformated.gtf.gz
  temp_dir: /home/santang3/scratch/glue/tmp

cluster:
  cores_per_node: 32

# Parameters for variant calling and SFS estimation with ANGSD
angsd:
  max_dp: 1250  # 2 x mean coverage from qualimap x # samples


