# Sample IDs as list
samples: ../../sequencing-prep/resources/low1_sampleSheet.txt
chromosomes: ../resources/chromosome_file.txt

results_prefix: ../results
raw_read_prefix: /node1nfs/archive/data/trifolium
temp_dir: /scratch/santang3/tmp 

# Include 10 urban and rural samples from Toronto data
toronto_data:
  bams: /research/projects/trifolium/toronto_gwsd/results/bam/final 
  samples: ../resources/toronto_samples_for_glue.txt

files:
  reference_genome: /research/references/trifolium/repens/GCA_005869975.1_AgR_To_v5/GCA_005869975.1_AgR_To_v5_genomic.fna
  gff: /research/references/trifolium/repens/GCA_005869975.1_AgR_To_v5/annotation_file/TrR.v5.renamed_reformated.gtf.gz

cluster:
  cores_per_node: 30

species_id:
  num_nt_db_files: 33  # Number of database files for NCBI's nt database (ftp://ftp.ncbi.nlm.nih.gov/blast/db/)

# Parameters for variant calling and SFS estimation with ANGSD
angsd:
  max_dp: 1250  # 2 x mean coverage from qualimap x # samples

