# Sample IDs as list
samples: ../resources/low1_libraryConcentrations.csv
chromosomes: ../resources/chromosome_file.txt

results_prefix: ../results
raw_read_prefix: /scratch/research/projects/trifolium/toronto_gwsd/data
temp_dir: /scratch/santang3/tmp 

files:
  reference_genome: /research/references/trifolium/repens/GCA_005869975.1_AgR_To_v5/GCA_005869975.1_AgR_To_v5_genomic.fna
  gff: /research/references/trifolium/repens/GCA_005869975.1_AgR_To_v5/annotation_file/TrR.v5.renamed_reformated.gtf.gz

cluster:
  cores_per_node: 30

species_id:
  num_nt_db_files: 33  # Number of database files for NCBI's nt database (ftp://ftp.ncbi.nlm.nih.gov/blast/db/)

# Samples to exclude based on QC
samples_to_exclude: ["Calgary_25_13", "Linkoping_8_8", "Melbourne_2_3", "Paris_15_14", "Paris_3_9"]
