# Sample IDs as list
samples: ../resources/glue_pc_sampleSheet.txt 
chromosomes: ../resources/chromosome_file.txt

# Path to used files
gff: ../resources/TrR.v5.renamed_reformated.gtf.gz
bam_path: /scratch/projects/trifolium/glue/pc/results/bam/4fold
qualimap_bamqc: ../resources/multiqc_qualimap_bamqc_genome_results_qualimap_bamqc.txt
ref_dir: ../resources/ref

# Path prefixes for results output by this pipeline
results_prefix: /scratch/projects/trifolium/glue/demography/glue_demography/results
temp_dir: /scratch/projects/trifolium/glue/demography/glue_demography/tmp
log_prefix: /scratch/projects/trifolium/glue/demography/glue_demography/results/log


# Parameters for variant calling and SFS estimation with ANGSD
# TODO: Some other parameters are hardcoded in the Snakefiles. Should probably move them here or move this to the Snakefile for consistency
angsd:
  max_dp: 4200   # ~2 x mean coverage from qualimap x # samples
