# Sample IDs as list
samples: ../resources/low1_libraryConcentrations.csv
chromosomes: ../resources/chromosome_file.txt

results_prefix: ../results
raw_read_prefix: /scratch/santang3/data 
temp_dir: /scratch/santang3/tmp 

# Include 10 urban and rural samples from Toronto data
toronto_data:
  bams: /scratch-deleted-2021-mar-20/santang3/toronto_gwsd/snakemake/results/bam/final
  samples: ../resources/toronto_samples_for_glue.txt

files:
  reference_genome: /scratch/n/nessrobe/santang3/clover-ref/ref_genome/GCA_005869975.1_AgR_To_v5_genomic.fna
  gff: /scratch/n/nessrobe/santang3/clover-ref/gff/TrR.v5.renamed_reformated.gtf.gz

cluster:
  cores_per_node: 40

species_id:
  num_nt_db_files: 33  # Number of database files for NCBI's nt database (ftp://ftp.ncbi.nlm.nih.gov/blast/db/)

# Parameters for variant calling and SFS estimation with ANGSD
angsd:
  max_dp: 1250  # 2 x mean coverage from qualimap x # samples
